### ISSUE TITLE
Exposing Events

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#10]
- Single click, Double click, Right click, Hover over pin, anything else that's relevant.

**Comment by siddharthlatest** [comment]
Use-case: Pins represent all the user data (checkins, reviews, different kinds of meta data), as a user - how can I add a popover functionality on hover to this lib?

**Comment by siddharthlatest** [comment]
@farhan687 what's the status on this?

**Comment by farhan687** [comment]
Events name - `markerOnIndex`, `markerOnDelete`, `markerOnClick`, `markerOnDblclick`, `markerOnMouseover`, `markerOnMouseout` 

Popover related props:
- We can specify events in `showPopoverOn` prop:  "onClick", "onMouseOver", "onDbClick"
- We can generate markup according to marker data.  pass the function in `popoverContent`, receive data in first argument and generate markup 
 
```
<AppbaseMap
...
showPopoverOn: "onClick"
popoverContent: {generateHtmlMarkup}
/>

generateHtmlMarkup(markerData) {
 return (<div>{markerData} </div>)
}
```

**Comment by siddharthlatest** [comment]
@farhan687 For indexing data to the map, we want to separate indexing and streaming updates.

Indexing can have multiple markers in the result that can be passed as an array for efficient representation.  

Streaming updates will have one marker object passed at a time.

**Comment by farhan687** [comment]
`markerOnIndex` is done over here: edd26fce63fc42c332003b9b1cf9504c4062b85f

Data will be received in following format:
```js
{
 method: 'historic',
 data: data
}

// or

{
 method: 'stream',
 data: data
}
```

**Comment by farhan687** [comment]
Right now I can see old method created earlier: `markerOnDelete`, Do we need such method?

**Comment by farhan687** [comment]
Now exposing following map events: 
onIdle, onMouseover, onMouseout, onClick, onDblclick, onDrag, onDragstart, onDragend, onMousemove, onMouseout, onMouseover, onResize, onRightclick, onTilesloaded, onBoundsChanged, onCenterChanged, onProjectionChanged, onTiltChanged, onZoomChanged
7f75c8f67b2d6203adf9cd5b7efed28cb6402d4f

[working demo](7f75c8f67b2d6203adf9cd5b7efed28cb6402d4f)
