### ISSUE TITLE
Explaining how to create custom queries

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#25]
1. Prop for creating custom queries, 
2. How inputs are passed to the query, 
3. Different examples.

**Comment by farhan687** [comment]
To create custom query for any sensor you can use defaultQuery property of depends, let's take a look at an example

*** Create custom query for inputField sensor

1) Let's use InputField sensor like this and set unique sensorId.
```
<InputField
	sensorId="InputSensor"
	title="Cities"
	placeholder="Search City (i.e London)"
/>
```

2) Let's use InputSensor dependency in AppbaseMap actuator.

as example:

```js
<AppbaseMap
	....
        depends={{
			   InputSensor: {"operation": "must", defaultQuery: this.cityQuery},
	}}
/>
```

3) In example cityQuery is the default query function which will be executed whenever sensor value will be changed, and this defaultQuery function will receive sensor value in first argument.

```js
cityQuery(value) {
	if(value) {
		return { 
			match: {
				'group.group_city.group_city_simple': value
			}
		};
	} else return null;
}
```

[Check working demo over here](http://opensource.appbase.io/reactive-maps/examples/CustomQuery/)
