### ISSUE TITLE
Simplifying installation steps

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#26]
We should support the following options:  

1. Complete CDN based dependencies (so no `npm`ing or `bower`ing), an it just works mode.  
2. npm based workflow with build dependencies just specified with a package.json single line like `browserify script.js -o bundle.js -t [ babelify --presets [ es2015 react ] ]`  
3. npm based workflow with a webpack.config.json file.

**Comment by farhan687** [comment]
1) CDN based example: https://github.com/farhan687/reactive-map-cdn
2) Browserify & Babel based example: https://github.com/farhan687/reactive-map-browserify
3) Webpack based example: https://github.com/farhan687/reactive-map-sample
