### ISSUE TITLE
Update range slider dots to have colors matching the line next to them

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#34]
Applied values that look good based on the browser dev tools styles.

![range slider image](https://i.imgur.com/QtHnPms.png)

![styles values image](https://i.imgur.com/sQcywk6.png)

**Comment by metagrover** [comment]
Fixed in [reactivebase](https://github.com/appbaseio/reactivebase/commit/03d5824a818df57b2c5aee7f7660943fea3e71e7)
