### ISSUE TITLE
ReactiveMap component behavior

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#35]
- [x] defaultZoom prop should be present and set to 13. Validation: accept values in range [0, 20].
- [x] defaultCenter prop should be added. It takes in a object with lat and lng key associated with valid float numbers `{ lat: 37.74, lng: -122.45 }`. lng can be an integer or float between [-180,180] and lat can be an integer or float between [-90, 90].
- [x] Rename `mapStyle` to `defaultMapStyle`.
- [x] Changing `size` prop should re-render the map results. Also, validate size to be between [1, 1000].
- [x] Validate `from` prop to be >= 0.
- [x] Add a prop for `autoCenter`.
- [x] Rename `defaultPin` prop to `defaultMarkerImage`.
- [x] Rename `streamPin` prop to `streamMarkerImage`.
- [x] Rename `rotateOnUpdate` prop to `autoMarkerPosition`.
- [x] Rename `clearOnEmpty` to `autoMapRender`.
- [x] Rename `markerCluster` to `setMarkerCluster`.
- [x] Rename `streamActiveTime` to `streamTTL`. `streamTTL` prop should be a Number that's >= 0 and <= 1000 (counted in seconds).
- [x] Remove `markerOnDelete` prop.
- [x] `showPopoverOn` prop should accept "click" and "mouseover" as valid values, don't need the On prefix in the values.
- [x] For branding, always use the white bg logo irrespective of the theme and display it at the bottom right of the map, to the left of the navigation (+/-) buttons.

**Comment by siddharthlatest** [comment]
- [ ] define `onPopoverTrigger` function for specifying popover content.

**Comment by metagrover** [comment]
Fixed here 93a8a23c4c2066be003a20a6bab16bd04e5dfb72
