### ISSUE TITLE
GeoDistance component behaviors

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#37]
- [x] add `stepValue` prop. Value should be floor((range.end - range.start)/2). Only applicable to GeoDistanceSlider component.
- [x] remove `size` prop
- [x] remove `APIKey` prop
- [x] validate `start` and `end` props in GeoDistanceDropdown component
- [x] `defaultSelected` prop should not be set by the component
- [ ] re-render storybook when `unit` prop is changed

**Comment by metagrover** [comment]
Fixed here 62ddec6208b190d2194cafe902d6ce19c462e308

**Comment by metagrover** [comment]
Fixed unit prop behavior deb6de348ec1324dcb7876915816e46c585cad1b
