### ISSUE TITLE
is there a plan for React Native support?

### ISSUE THREAD

**Issue by faceyspacey** [appbaseio/reactivemaps#39]

**Comment by siddharthlatest** [comment]
@faceyspacey yes, we plan to support React Native.

**Comment by siddharthlatest** [comment]
Update here: We will be supporting a React Native version of the library, but perhaps a first good step would be to optimize the library to create mobile responsive maps. This will be released in the upcoming `v1.0.0` and a React Native version would be in the major release (or a separate repo if the code differences are substantial).

**Comment by metagrover** [comment]
Primary support for React Native maps has been added. Docs are available [here](https://opensource.appbase.io/reactive-manual/native/components/reactivemap.html) 🎉
