### ISSUE TITLE
ReactiveMap: Execute initial view query irrespective of setSearchAsMove prop

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#40]
`setSearchAsMove` prop controls if the query should be re-run when the map bounds change. However, currently it also blocks the query from executing in the initial view.

The prop value should not affect the initial rendering of results. It should only affect the result rendering behavior after the fact.

**Comment by farhan687** [comment]
Fixed here fa77d4fa52406926bddd6cbaa1567217f6c7abb1
