### ISSUE TITLE
Add popoverTTL prop in ReactiveMaps

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#46]
There can be a more accessible way to auto-close popover behavior.

`popoverTTL` takes a `Number` which can be set b/w 0 and 60 (representing seconds) that the popover should be open for. The name is kept to be similar to another such prop streamTTL.

**Comment by farhan687** [comment]
Fixed here: ef65d7b48675e5f6748b24ef6b23b1378da1446b

**Comment by siddharthlatest** [comment]
- [ ] we should make the minimum value to be 1 (as 0 seconds doesn't make sense).
