### ISSUE TITLE
ReactiveMap props behavior changes

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#49]
To improve the component prop consistencies with other components and how we deal with geolocation data, we will:

- [x] Merge containerStyle prop into `componentStyle` so we have a single place do add all the custom styles.
- [x] Replace "lng" key with "lon" key in the `defaultCenter` prop

**Comment by farhan687** [comment]
Fixed here: f117cf33a07729372548934c26e576d4e5e51584 984d5d0a47ef4b1772da9557ebbcfe98e03e0c4d

defaultCenter new format is {lat: x, lon: y}.
