### ISSUE TITLE
Unable to retrieve data from a markerCluster

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#50]
Current marker cluster behavior when there are multiple items at the same lat, lon.

![marker_behavior](https://cloud.githubusercontent.com/assets/630042/24135463/ddceef24-0e2f-11e7-9cd4-778a3e7d4086.gif)

Ideally, in this case - we should pass a popover context with data from all the items to the **onPopoverTrigger** function.

Reference issue: https://github.com/tomchentw/react-google-maps/issues/420

**Comment by farhan687** [comment]
markerCluster don't support popover, so it is not possible to setup popover on markerCluster. We need to search for another possible solution.

**Comment by metagrover** [comment]
This has been fixed in v2 - [here](https://github.com/appbaseio/reactivesearch/commit/7c536bc3a520d88baeb4b2cf2e769decdb4fc392)
