### ISSUE TITLE
Refactoring Reactivemaps examples

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#54]
We should test for functionality and code accessibility in all the current examples.

- [x] Removal of itemMarkup function
- [x] Use of onData() instead of onAllData()
- [x] Spell checks
- [x] Prop name checks and removing any unneeded / deprecated props

**Comment by siddharthlatest** [comment]
- [ ] In Heatmap, we will apply a 24h _ttl value. It should work by default.
- [ ] Now currently shows London pins in Somalia. Possible issue with onData() method.

**Comment by farhan687** [comment]
Fixed here 0f74de5d5ff472c31f28bd4087223e58a6ad794d
