### ISSUE TITLE
GeoDistance Components: Exposing New Props

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivemaps#56]
- [x] **autoLocation**, a boolean prop which is set to `true` by default and can be set to `false`. Similar to the one we have in PlacesSearch.
- [x] In GeoDistanceDropdown, a **placeholderDropdown** prop which allows setting a placeholder for the dropdown element.

**Comment by siddharthlatest** [comment]
@grover Has this been fixed?

**Comment by metagrover** [comment]
Yes
