### ISSUE TITLE
ReactiveMap throws a 400 when used with DataSearch/NativeList

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactivemaps#69]
Reference example on [playground](https://opensource.appbase.io/playground/?knob-title=Reactive%20maps&knob-showMarkers=true&knob-filterLabel=GeoDistance%20filter&knob-defaultSelected=%7B%22location%22%3A%22London%22%2C%22distance%22%3A5%7D&knob-rangeLabels=%7B%22start%22%3A%22Start%22%2C%22end%22%3A%22End%22%7D&knob-range=%7B%22start%22%3A0%2C%22end%22%3A50%7D&knob-autoMarkerPosition=false&knob-streamMarkerImage=https%3A%2F%2Fcdn.rawgit.com%2Fappbaseio%2Freactivemaps%2F6500c73a%2Fdist%2Fimages%2Fstream-pin.png&knob-showMapStyles=false&knob-URLParams%20%28not%20visible%20on%20storybook%29=true&knob-showFilter=true&knob-autoMapRender=true&knob-stepValue=1&knob-showPopoverOn=click&knob-setMarkerCluster=true&knob-streamTTL=5&knob-setSearchAsMove=false&knob-defaultMarkerImage=https%3A%2F%2Fcdn.rawgit.com%2Fappbaseio%2Freactivemaps%2F6500c73a%2Fdist%2Fimages%2Fhistoric-pin.png&knob-size=100&knob-autoLocation=true&knob-streamAutoCenter=true&knob-unit=mi&knob-autoCenter=true&knob-placeholder=Search%20Location&knob-defaultZoom=13&knob-showSearchAsMove=true&knob-defaultMapStyle=Standard&knob-defaultCenter=%7B%22lat%22%3A37.74%2C%22lon%22%3A-122.45%2C%22lng%22%3A-122.45%7D&selectedKind=map%2FReactiveMap&selectedStory=Playground&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs).

**Comment by metagrover** [comment]
Invalid issue: The problem was with the `meetup2` app mappings. Updated the app in playground.
