### ISSUE TITLE
Update react-google-maps

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactivemaps#75]
Currently, we're using `react-google-maps@^4.11.0`. We need to update [this package](https://tomchentw.github.io/react-google-maps/). 

Looking at the [changelog](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md), it seems we need to fix some breaking changes.
A major change I could find is [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#breaking-changes-2), though you can go ahead and find other breaking changes as well.

We're using this package in [ReactiveMaps](https://github.com/appbaseio/reactivemaps/blob/dev/app/actuators/ReactiveMap.js) actuator.

Workflow breakdown:
- [x] View [changelog](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md) and find all breaking changes from `4.11.0` to latest.
- [x] Update react-google-maps package
- [x] Refactor [ReactiveMaps](https://github.com/appbaseio/reactivemaps/blob/dev/app/actuators/ReactiveMap.js) code
- [x] Test by using storybook example `npm run storybook`
- [ ] Send PR. :tada:

**Comment by vcapretz** [comment]
hey @dhruvdutt I'm working on this one!

**Comment by dhruvdutt** [comment]
Awesome. @vcapretz
Good luck.

**Comment by siddharthlatest** [comment]
@vcapretz appreciate the outreach. You can self-assign the issue so we can make block this from being assigned to someone.

**Comment by vcapretz** [comment]
hey @siddharthlatest I just sent the PR, but I'm not able to assign myself in this issue

**Comment by siddharthlatest** [comment]
- [ ] Update the example
- [ ] Update the doc for [ReactiveMap component](https://opensource.appbase.io/reactive-manual/v1/map-components/ReactiveMap.html)

**Comment by metagrover** [comment]
Fixed here: a4ca7440a26f87d0877add8c8da4058948897e2c and 778037ce5ccc0962242d8dbec2e6bdcd238e0e5d
