### ISSUE TITLE
appbaseRef is marked as required

### ISSUE THREAD

**Issue by justinsoong** [appbaseio/reactivemaps#78]
Failed context type: The context `appbaseRef` is marked as required in `ReactiveMap`, but its value is `undefined`.

Getting the error above which i think is why my hits are not rendering, any clues

**Comment by justinsoong** [comment]
Reactivemaps doesn't seem to work out of the box with ReactiveSearch components, the docs were quite brief on using Reactivemaps in conjunction with ReactiveSearch

**Comment by siddharthlatest** [comment]
Hey @justinsoong, currently ReactiveMaps doesn't work with ReactiveSearch. We will be upgrading it to the new architecture we are using with ReactiveSearch 2.0.

**Comment by justinsoong** [comment]
Thanks man @siddharthlatest any time frame? really like the in built styles which come with reactivesearch components, could you point me to the default stylesheet for reactivemaps?
