### ISSUE TITLE
Error thrown on ReactiveMap Basic example

### ISSUE THREAD

**Issue by danedavid** [appbaseio/reactivemaps#79]
Steps to reproduce:
1. Go to https://opensource.appbase.io/reactivemaps/playground/?selectedKind=ReactiveMap&selectedStory=Basic

2. Click on 'Search as I move the map' option.

The following error is thrown in console:
```
Uncaught TypeError: this.props.onRemove is not a function
    at ItemCheckboxList.handleListClick (preview.06b64fe8ca7d720f7050.bundle.js:1)
    at ListItem.handleClick (preview.06b64fe8ca7d720f7050.bundle.js:1)
```

**Comment by divyanshu013** [comment]
Hi @danedavid, we're continuing the work on Reactive Maps v2 in the [reactivesearch](https://github.com/appbaseio/reactivesearch) repo. The updated playground is available [here](https://opensource.appbase.io/playground/?selectedKind=Map%20Components%2FReactiveMap&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) :)
