### ISSUE TITLE
Live Examples not working

### ISSUE THREAD

**Issue by delkant** [appbaseio/reactivemaps#81]
Hi! Can you check on your live examples? I couldn't open any of the listed in the readme/home page.

Thanks.

**Comment by divyanshu013** [comment]
Hi @delkant, reactivemaps development has been moved to the reactivesearch repo. You can find it here https://github.com/appbaseio/reactivesearch/tree/dev/packages/maps

Here's the quickstart guide https://opensource.appbase.io/reactive-manual/getting-started/reactivemaps.html
