### ISSUE TITLE
All links on the website lead to the reactivesearch repo

### ISSUE THREAD

**Issue by RusinovAnton** [appbaseio/reactivemaps#82]
https://github.com/appbaseio/reactivemaps/search?q=reactivesearch&unscoped_q=reactivesearch

**Comment by metagrover** [comment]
Yes, that's because the latest version of this project(which is a complete re-write) is maintained at the reactivesearch repo, where we have reactivesearch for web, native and maps.

Here, we only host the reactivemaps website and have the deprecated version 1.x in the other branches.
