### ISSUE TITLE
Could not find "store" in the context of "Connect(ReactiveMap)"

### ISSUE THREAD

**Issue by digggggggggg** [appbaseio/reactivemaps#96]
I'm getting this error and I'm not sure where to go from here:
```Uncaught Invariant Violation: Could not find "store" in the context of "Connect(ReactiveMap)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(ReactiveMap) in connect options.```

![image](https://user-images.githubusercontent.com/182178/63651126-a2d63c80-c749-11e9-9e30-1df560f51cd5.png)

![image](https://user-images.githubusercontent.com/182178/63651027-f005de80-c748-11e9-848f-fc0e1a559191.png)

**Comment by siddharthlatest** [comment]
@digggggggggg Which version of ReactiveMaps are you on? Does this happen with `3.0.0-beta.2`?

**Comment by digggggggggg** [comment]
Yes! Is that the problem? What's the latest stable version? What version should I use?

**Comment by digggggggggg** [comment]
I found the cause of the problem. there was a conflict caused by multiple package.json and node_modules folders in the project.
